### ISSUE TITLE
Eventsページの上がでかい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traPortfolio-Dashboard#172]
PRが出てる間に他のPRで変更加えたのを忘れてた
Contestsページとかを参考に
```css
.header {
  margin-bottom: 2rem;
}
```
にすると直る
![image](https://github.com/traPtitech/traPortfolio-Dashboard/assets/83744975/e09a6a36-6368-40dc-b703-35bc633d7d4c)
